name: Bug report
description: File a bug report
labels: ["bug"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Please confirm you are using the latest version and you have read and understood the configuration.
      description: This helps us avoid common issues and resolve real problems faster.
      options:
        - label: I am using the latest version
          required: true
        - label: I have read through the config
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the issue
      description: Describe how to reproduce the issue step by step
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos (you can drag and drop files or paste links)
      description: If applicable, add screenshots to help explain your problem (you can drag and drop files or paste links).
