name: Feature request
description: Request a feature to be added to BodyHealth
labels: ["enhancement"]
body:
  - type: textarea
    id: suggestion
    attributes:
      label: What should be added or changed?
      description: "Provide a brief and clear explanation of the change or addition you're suggesting."
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why should we consider your suggestion?
      description: Outline the reasons why this change or addition would be beneficial or necessary.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos (you can drag and drop files or paste links)
      description: If applicable, add screenshots to help explain your problem (you can drag and drop files or paste links).
