name: Question
description: Ask a question about BodyHealth
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Ask your question here
      description: Make sure to provide all necessary information.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos (you can drag and drop files or paste links)
      description: If applicable, add screenshots to help explain your problem (you can drag and drop files or paste links).
